[web]
# Bind interface(s)
bind = ["127.0.0.1:8701"]

[github]
# This should be a github personal access token that has access to read & write
# github release assets in the repo you plan to run this on
token = "github_pat_asdadsasd"

# If set to false, this will skip the webhook secret verification.
# Only set this to false if you're doing testing with local requests to the API
verify_signature = true

# The webhook secret specified in the GitHub webhook
secret = "webhook_secret"

# The repo to use for building, and to validate webhooks with
# https://github.com/{repo_owner}/{repo_name}
repo_owner = "pajlada"
repo_name = "chatterino2"

# List of branches & their respective releases
branches = [ { name = "master", release_id = 82423741 } ]
